
export { default as authRouter } from './authsR'
export { default as usersRouter } from './usersR'
export { default as proyectsRouter } from './projectsR'
export { default as tasksRouter } from './tasksR'
export { default as notisRouter } from './notisR'
export { default as clientRouter } from './clientR'
export { default as eventRouter } from './eventsR'
export { default as reposRouter } from './reposR'
export { default as gitlabRouter } from './gitlabR'
export { default as commentsRouter } from './commentsR'
export { default as searcherRouter } from './searcherR'
export { default as friendsRouter } from './friendsR'
export { default as likesRouter } from './likesR'
export { default as extensionRouter } from './extensionR'
